[package]
name = "librxe-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.59"

[dependencies]
libc = "0.2.126"
rdma-sys = { git ="https://github.com/Gwzlchn/rdma-sys"}
